[versions]
archunit = "1.4.1"
detekt = "1.23.8"
foojay-resolver = "1.0.0"
junit = "5.13.4"
jackson = "2.22"
kora = "1.2.18"
kotlin = "2.4.10"
openapi-generator = "7.24.0"
spotless = "7.2.1"

[libraries]
archunit-junit5 = { module = "com.tngtech.archunit:archunit-junit5", version.ref = "archunit" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
kora-bom = { module = "ru.tinkoff.kora:kora-parent", version.ref = "kora" }
kora-config-hocon = { module = "ru.tinkoff.kora:config-hocon" }
kora-database-flyway = { module = "ru.tinkoff.kora:database-flyway" }
kora-database-jdbc = { module = "ru.tinkoff.kora:database-jdbc" }
kora-http-server-undertow = { module = "ru.tinkoff.kora:http-server-undertow" }
kora-json-module = { module = "ru.tinkoff.kora:json-module" }
kora-logging-logback = { module = "ru.tinkoff.kora:logging-logback" }
kora-annotation-processors = { module = "ru.tinkoff.kora:annotation-processors", version.ref = "kora" }
postgresql = { module = "org.postgresql:postgresql", version = "42.7.7" }

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
openapi-generator = { id = "org.openapi.generator", version.ref = "openapi-generator" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
